AppName = "tokenmed"

BaseUrl = "https://tokenbest.io"

CDNUrl = "https://static.tianxi100.com/"

RedPacketShareLink = "https://tokenmama.io/rp.html#/show/"

Port = 8007

LogPath = "/tmp/tokenme"

Debug = true

Geth = "https://mainnet.infura.io/NlT37dDxuLT2tlZNw3It"

EthplorerKey = "freekey"

SlackToken = "xoxp-340014960567-338241194720-339563622341-94fcb61ce9353b2b0f5a86d4e99580d8"

SlackAdminChannelID = "G9Y7METUG"

GeoIP = "/etc/GeoLite2-Country.mmdb"

TokenSalt = "20eefe8d82ba3ca8a417e14a48d24632bc35bbd7"

LinkSalt = "20eefe8d82ba3ca8a417e14a48d24632bc35bbd7"

TwilioToken = "khWDR6abzUyqzM1WHy9Tfq7P2jRoEhLA"

TelegramBotToken = "547738949:AAFJLOcFctmNEK5wDRDpWP8lE107T7p8XQU"

TelegramBotName = "TokenmeBot"

WXAppId = "wxed7bca95735072e9"

WXSecret = "57d8cd91005b4e916dc9f4bb563f06ec"

SentryDSN = "https://b7c6f2e4200a444c99f6b92aca5c372c:849b8bfea55c4d4cbca578ec68a861bb@sentry.io/994357"

AirdropCommissionFee = 2

RedPacketCommissionFee = 50

DealerIncomeWallet = "0x70d69d3aaed7b98c8b0bb0e8bce5caf40e889c69"

DealerContractCreateGasPrice = 8

DealerContractCreateGasLimit = 210000

RedPacketIncomeWallet = "0x70d69d3aaed7b98c8b0bb0e8bce5caf40e889c69"

RedPacketGasPrice = 8

RedPacketGasLimit = 210000


[MySQL]
Host = "tokenme.c4evkvyvqy7m.ap-northeast-1.rds.amazonaws.com:3306"
User = "tokenme"
Passwd = "tokenmeCRICSUKI2"
DB = "tokenme"

[Redis]
Master = "tokenme-001.0gguww.0001.apne1.cache.amazonaws.com:6379"
Slave = "tokenme-002.0gguww.0001.apne1.cache.amazonaws.com:6379"

